Repository honey-moa/honey-moa-server, pull requests merged in 2025-01, with the labels that each got.

#19 회원가입 RequestBodyDto에서 name 삭제
  src/apis/user/dtos/request/create-user.request-body-dto.ts
Labels: Bugfix

#21 ZodError/BadRequestExceptionFilter 구현, swaggerBuilder 기능 추가
  src/apis/post/controllers/post.controller.ts
  src/apis/post/controllers/post.swagger.ts
  src/apis/token/controllers/token.controller.ts
  src/apis/token/controllers/token.swagger.ts
  src/apis/user/controllers/user.controller.ts
  src/apis/user/controllers/user.swagger.ts
  src/app.controller.ts
  src/bootstrap.service.ts
  src/libs/api/decorators/api-internal-server-error-builder.decorator.ts
  src/libs/api/decorators/get-user-id.decorator.ts
  src/libs/exceptions/client-errors/filters/bad-request.exception-filter.ts
  src/libs/exceptions/etc-errors/filters/http-path-not-found.exception-filter.ts
  src/libs/exceptions/exceptions.module.ts
  src/libs/exceptions/http.exception.ts
  src/libs/exceptions/server-errors/filters/http-internal-server-error.exception-filter.ts
  src/libs/exceptions/server-errors/filters/http-process-error.exception-filter.ts
  src/libs/exceptions/server-errors/filters/http-remainder.exception-filter.ts
  src/libs/exceptions/server-errors/filters/zod-error.exception-filter.ts
  src/libs/guards/providers/basic-auth.guard.ts
Labels: Feat, Modify

#24 비밀번호 변경 API
  prisma/migrations/20250103053713_add_type_user_email_verify_tokens/migration.sql
  prisma/migrations/20250103055739_drop_trigger_user_email_verify_tokens_updated_at/migration.sql
  prisma/migrations/20250103060314_modify_user_verify_token_type_enum/migration.sql
  prisma/migrations/20250103064426_add_is_used_in_user_verify_tokens/migration.sql
  prisma/migrations/20250103072103_modify_enum_upper_snakecase/migration.sql
  prisma/schema.prisma
  src/apis/token/controllers/token.controller.ts
  src/apis/user/application/event-handlers/create-user-email-verify-token.domain-event-handler.ts
  src/apis/user/commands/send-password-change-verification-email/send-password-change-verification-email.command-handler.ts
  src/apis/user/commands/send-password-change-verification-email/send-password-change-verification-email.command.ts
  src/apis/user/commands/send-verification-email/send-verification-email.command-handler.ts
  src/apis/user/commands/update-user-password/update-user-password.command-handler.ts
  src/apis/user/commands/update-user-password/update-user-password.command.ts
  src/apis/user/commands/verify-user-email/verify-user-email.command-handler.ts
  src/apis/user/controllers/user.controller.ts
  src/apis/user/controllers/user.swagger.ts
  src/apis/user/domain/user-email-verify-token/user-email-verify-token.entity-interface.ts
  src/apis/user/domain/user-email-verify-token/user-email-verify-token.entity.ts
  src/apis/user/domain/user-verify-token/user-verify-token.entity-interface.ts
  src/apis/user/domain/user-verify-token/user-verify-token.entity.ts
  src/apis/user/domain/user.entity-interface.ts
  src/apis/user/domain/user.entity.ts
  src/apis/user/dtos/request/send-password-change-verification-email.request-dto.ts
  src/apis/user/dtos/request/update-password.request-dto.ts
  src/apis/user/mappers/user-email-verify-token.mapper.ts
  src/apis/user/mappers/user-verify-token.mapper.ts
  src/apis/user/mappers/user.mapper.ts
  src/apis/user/repositories/user.repository-port.ts
  src/apis/user/repositories/user.repository.ts
  src/apis/user/types/user.constant.ts
  src/apis/user/types/user.type.ts
  src/apis/user/user.module.ts
  src/configs/app.route.ts
  src/libs/api/pipes/parse-email.pipe.ts
  src/libs/ddd/repository.port.ts
  src/libs/email/services/email.service-port.ts
  src/libs/email/services/email.service.ts
  src/libs/exceptions/http.exception.ts
  src/libs/exceptions/types/errors/user/user-error-code.constant.ts
  src/libs/exceptions/types/errors/user/user-error-message.constant.ts
Labels: Feat

#25 Deploy to main
  prisma/migrations/20250103053713_add_type_user_email_verify_tokens/migration.sql
  prisma/migrations/20250103055739_drop_trigger_user_email_verify_tokens_updated_at/migration.sql
  prisma/migrations/20250103060314_modify_user_verify_token_type_enum/migration.sql
  prisma/migrations/20250103064426_add_is_used_in_user_verify_tokens/migration.sql
  prisma/migrations/20250103072103_modify_enum_upper_snakecase/migration.sql
  prisma/schema.prisma
  src/apis/token/controllers/token.controller.ts
  src/apis/user/application/event-handlers/create-user-email-verify-token.domain-event-handler.ts
  src/apis/user/commands/send-password-change-verification-email/send-password-change-verification-email.command-handler.ts
  src/apis/user/commands/send-password-change-verification-email/send-password-change-verification-email.command.ts
  src/apis/user/commands/send-verification-email/send-verification-email.command-handler.ts
  src/apis/user/commands/update-user-password/update-user-password.command-handler.ts
  src/apis/user/commands/update-user-password/update-user-password.command.ts
  src/apis/user/commands/verify-user-email/verify-user-email.command-handler.ts
  src/apis/user/controllers/user.controller.ts
  src/apis/user/controllers/user.swagger.ts
  src/apis/user/domain/user-email-verify-token/user-email-verify-token.entity-interface.ts
  src/apis/user/domain/user-email-verify-token/user-email-verify-token.entity.ts
  src/apis/user/domain/user-verify-token/user-verify-token.entity-interface.ts
  src/apis/user/domain/user-verify-token/user-verify-token.entity.ts
  src/apis/user/domain/user.entity-interface.ts
  src/apis/user/domain/user.entity.ts
  src/apis/user/dtos/request/send-password-change-verification-email.request-dto.ts
  src/apis/user/dtos/request/update-password.request-dto.ts
  src/apis/user/mappers/user-email-verify-token.mapper.ts
  src/apis/user/mappers/user-verify-token.mapper.ts
  src/apis/user/mappers/user.mapper.ts
  src/apis/user/repositories/user.repository-port.ts
  src/apis/user/repositories/user.repository.ts
  src/apis/user/types/user.constant.ts
  src/apis/user/types/user.type.ts
  src/apis/user/user.module.ts
  src/configs/app.route.ts
  src/libs/api/pipes/parse-email.pipe.ts
  src/libs/ddd/repository.port.ts
  src/libs/email/services/email.service-port.ts
  src/libs/email/services/email.service.ts
  src/libs/exceptions/http.exception.ts
  src/libs/exceptions/types/errors/user/user-error-code.constant.ts
  src/libs/exceptions/types/errors/user/user-error-message.constant.ts
Labels: Feat

#26 마이그레이션 깨진 부분 수정
  prisma/migrations/20241217072408_user_post/migration.sql
  prisma/migrations/20250103053713_add_type_user_email_verify_tokens/migration.sql
  prisma/migrations/20250103060314_modify_user_verify_token_type_enum/migration.sql
  prisma/migrations/20250103072103_modify_enum_upper_snakecase/migration.sql
Labels: DB

#27 깨진 마이그레이션 수정
  prisma/migrations/20241217072408_user_post/migration.sql
  prisma/migrations/20250103053713_add_type_user_email_verify_tokens/migration.sql
  prisma/migrations/20250103060314_modify_user_verify_token_type_enum/migration.sql
  prisma/migrations/20250103072103_modify_enum_upper_snakecase/migration.sql
Labels: DB, Bugfix

#29 User Entity의 LoginCredential 삭제
  prisma/migrations/20250103053713_add_type_user_email_verify_tokens/migration.sql
  prisma/migrations/20250105064314_user_connections/migration.sql
  prisma/schema.prisma
  src/apis/user/commands/create-user/create-user.command-handler.ts
  src/apis/user/commands/update-user-password/update-user-password.command-handler.ts
  src/apis/user/domain/events/user-is-email-verified-modified.event.ts
  src/apis/user/domain/events/user-login-credential-updated.event.ts
  src/apis/user/domain/events/user-password-updated.event.ts
  src/apis/user/domain/user.entity-interface.ts
  src/apis/user/domain/user.entity.ts
  src/apis/user/domain/value-objects/login-credentials.value-object.ts
  src/apis/user/mappers/user.mapper.ts
  src/apis/user/repositories/user.repository.ts
  src/apis/user/types/user.constant.ts
  src/apis/user/types/user.type.ts
  src/libs/api/pipes/parse-positive-int.pipe.spec.ts
  src/libs/guard.ts
Labels: Modify

#30 CODEOWNERS 수정
  .github/CODEOWNERS
Labels: Setup

#31 Deploy to main
  .github/CODEOWNERS
  prisma/migrations/20250103053713_add_type_user_email_verify_tokens/migration.sql
  prisma/migrations/20250105064314_user_connections/migration.sql
  prisma/schema.prisma
  src/apis/user/commands/create-user/create-user.command-handler.ts
  src/apis/user/commands/update-user-password/update-user-password.command-handler.ts
  src/apis/user/domain/events/user-is-email-verified-modified.event.ts
  src/apis/user/domain/events/user-login-credential-updated.event.ts
  src/apis/user/domain/events/user-password-updated.event.ts
  src/apis/user/domain/user.entity-interface.ts
  src/apis/user/domain/user.entity.ts
  src/apis/user/domain/value-objects/login-credentials.value-object.ts
  src/apis/user/mappers/user.mapper.ts
  src/apis/user/repositories/user.repository.ts
  src/apis/user/types/user.constant.ts
  src/apis/user/types/user.type.ts
  src/libs/api/pipes/parse-positive-int.pipe.spec.ts
  src/libs/guard.ts
Labels: Modify

#32 strategy 및 guard의 역할에 맞게 코드 수정, 회원가입, 로그인을 auth 모듈에서 처리하도록 수정
  src/apis/apis.module.ts
  src/apis/auth/auth.module.ts
  src/apis/auth/commands/generate-access-token/generate-access-token.command-handler.ts
  src/apis/auth/commands/generate-access-token/generate-access-token.command.ts
  src/apis/auth/controllers/auth.controller.ts
  src/apis/auth/controllers/auth.swagger.ts
  src/apis/auth/dtos/request/sign-up.request-body-dto.ts
  src/apis/post/controllers/post.controller.ts
  src/apis/token/commands/generate-access-token/generate-access-token.command-handler.ts
  src/apis/token/controllers/token.controller.ts
  src/apis/token/controllers/token.swagger.ts
  src/apis/token/token.module.ts
  src/apis/user/controllers/user.controller.ts
  src/apis/user/controllers/user.swagger.ts
  src/apis/user/user.module.ts
  src/configs/app.route.ts
  src/libs/api/decorators/get-user-id.decorator.ts
  src/libs/api/decorators/user.decorator.ts
  src/libs/app-jwt/factories/jwt-module-options.factory.ts
  src/libs/app-jwt/services/app-jwt.service.ts
  src/libs/app-jwt/types/app-jwt.interface.ts
  src/libs/exceptions/server-errors/filters/zod-error.exception-filter.ts
  src/libs/exceptions/types/errors/auth/auth-error-code.constant.ts
  src/libs/exceptions/types/errors/auth/auth-error-message.constant.ts
  src/libs/exceptions/types/errors/error-code.constant.ts
  src/libs/exceptions/types/errors/error-message.constant.ts
  src/libs/exceptions/types/errors/token/token-error-message.constant.ts
  src/libs/guards/providers/basic-auth.guard.ts
  src/libs/guards/providers/jwt-bearer-auth.guard.ts
  src/libs/guards/providers/jwt-bearer-auth.strategy.ts
  src/libs/interceptors/logging/request-response-logging.interceptor.ts
  src/main.ts
Labels: Refactor

#36 유저 커넥션 조회, 수락/거절/취소 API 추가
  prisma/migrations/20250109105012_add_user_connection_status_enum/migration.sql
  prisma/migrations/20250109105216_modify_enum_name/migration.sql
  prisma/schema.prisma
  src/apis/user/commands/user-connection/update-user-connection/update-user-connection.command-handler.ts
  src/apis/user/commands/user-connection/update-user-connection/update-user-connection.command.ts
  src/apis/user/controllers/user-connection/user-connection.controller.ts
  src/apis/user/controllers/user-connection/user-connection.swagger.ts
  src/apis/user/controllers/user.controller.ts
  src/apis/user/domain/user-connection/user-connection.entity-interface.ts
  src/apis/user/domain/user-connection/user-connection.entity.ts
  src/apis/user/domain/user.entity-interface.ts
  src/apis/user/domain/user.entity.ts
  src/apis/user/dtos/response/hydrated-user.response-dto.ts
  src/apis/user/dtos/user-connection/request/find-user-connections.request-query-dto.ts
  src/apis/user/dtos/user-connection/request/update-user-connection.request-body-dto.ts
  src/apis/user/dtos/user-connection/response/user-connection.response-dto.ts
  src/apis/user/mappers/user-connection.mapper.ts
  src/apis/user/queries/find-users/find-users.query-handler.ts
  src/apis/user/queries/find-users/find-users.query.ts
  src/apis/user/queries/user-connection/find-user-connections/find-user-connections.query-handler.ts
  src/apis/user/queries/user-connection/find-user-connections/find-user-connections.query.ts
  src/apis/user/repositories/user.repository-port.ts
  src/apis/user/repositories/user.repository.ts
  src/apis/user/types/user.constant.ts
  src/apis/user/user.module.ts
  src/configs/app.route.ts
  src/libs/api/dtos/request/pagination-base.request-query-dto.ts
  src/libs/ddd/repository.port.ts
  src/libs/exceptions/types/errors/user/user-error-code.constant.ts
  src/libs/exceptions/types/errors/user/user-error-message.constant.ts
Labels: Feat

#37 Deploy to main
  prisma/migrations/20250109105012_add_user_connection_status_enum/migration.sql
  prisma/migrations/20250109105216_modify_enum_name/migration.sql
  prisma/schema.prisma
  src/apis/user/commands/user-connection/update-user-connection/update-user-connection.command-handler.ts
  src/apis/user/commands/user-connection/update-user-connection/update-user-connection.command.ts
  src/apis/user/controllers/user-connection/user-connection.controller.ts
  src/apis/user/controllers/user-connection/user-connection.swagger.ts
  src/apis/user/controllers/user.controller.ts
  src/apis/user/domain/user-connection/user-connection.entity-interface.ts
  src/apis/user/domain/user-connection/user-connection.entity.ts
  src/apis/user/domain/user.entity-interface.ts
  src/apis/user/domain/user.entity.ts
  src/apis/user/dtos/response/hydrated-user.response-dto.ts
  src/apis/user/dtos/user-connection/request/find-user-connections.request-query-dto.ts
  src/apis/user/dtos/user-connection/request/update-user-connection.request-body-dto.ts
  src/apis/user/dtos/user-connection/response/user-connection.response-dto.ts
  src/apis/user/mappers/user-connection.mapper.ts
  src/apis/user/queries/find-users/find-users.query-handler.ts
  src/apis/user/queries/find-users/find-users.query.ts
  src/apis/user/queries/user-connection/find-user-connections/find-user-connections.query-handler.ts
  src/apis/user/queries/user-connection/find-user-connections/find-user-connections.query.ts
  src/apis/user/repositories/user.repository-port.ts
  src/apis/user/repositories/user.repository.ts
  src/apis/user/types/user.constant.ts
  src/apis/user/user.module.ts
  src/configs/app.route.ts
  src/libs/api/dtos/request/pagination-base.request-query-dto.ts
  src/libs/ddd/repository.port.ts
  src/libs/exceptions/types/errors/user/user-error-code.constant.ts
  src/libs/exceptions/types/errors/user/user-error-message.constant.ts
Labels: Feat

#39 swagger description 수정
  src/apis/user/dtos/user-connection/request/find-user-connections.request-query-dto.ts
Labels: Doc

#40 WinstonLogger 세팅 및 에러로그 Cloudwatch로 전송
  package-lock.json
  package.json
  src/bootstrap.service.ts
  src/libs/core/app-config/app-config.module.ts
  src/libs/core/app-config/constants/app-config.constant.ts
  src/libs/exceptions/server-errors/filters/zod-error.exception-filter.ts
  src/libs/exceptions/services/http-exception.service.ts
  src/libs/libs.module.ts
  src/libs/logger/factories/winston-logger-options.factory.ts
  src/main.ts
Labels: Setup, Feat

#41 Deploy to main
  package-lock.json
  package.json
  src/apis/user/dtos/user-connection/request/find-user-connections.request-query-dto.ts
  src/bootstrap.service.ts
  src/libs/core/app-config/app-config.module.ts
  src/libs/core/app-config/constants/app-config.constant.ts
  src/libs/exceptions/server-errors/filters/zod-error.exception-filter.ts
  src/libs/exceptions/services/http-exception.service.ts
  src/libs/libs.module.ts
  src/libs/logger/factories/winston-logger-options.factory.ts
  src/main.ts
Labels: Feat

#43 객체 로깅 시 cloudwatch에 전송 안되는 문제 해결
  src/libs/exceptions/server-errors/filters/zod-error.exception-filter.ts
  src/libs/exceptions/services/http-exception.service.ts
  src/libs/logger/factories/winston-logger-options.factory.ts
Labels: Refactor

#44 Deploy to main
  src/libs/exceptions/server-errors/filters/zod-error.exception-filter.ts
  src/libs/exceptions/services/http-exception.service.ts
  src/libs/logger/factories/winston-logger-options.factory.ts
Labels: Refactor

#45 connection 단일 조회 및 블로그, 채팅방 생성 API
  prisma/migrations/20250113094556_create_chat_rooms_and_blogs/migration.sql
  prisma/schema.prisma
  src/apis/user/commands/user-connection/blog/create-blog/create-blog.command-handler.ts
  src/apis/user/commands/user-connection/blog/create-blog/create-blog.command.ts
  src/apis/user/commands/user-connection/chat-room/create-chat-room/create-chat-room.command-handler.ts
  src/apis/user/commands/user-connection/chat-room/create-chat-room/create-chat-room.command.ts
  src/apis/user/commands/user-connection/create-user-connection/create-user-connection.command-handler.ts
  src/apis/user/commands/user-connection/update-user-connection/update-user-connection.command-handler.ts
  src/apis/user/controllers/user-connection/blog/blog.controller.ts
  src/apis/user/controllers/user-connection/blog/blog.swagger.ts
  src/apis/user/controllers/user-connection/chat-room/chat-room.controller.ts
  src/apis/user/controllers/user-connection/chat-room/chat-room.swagger.ts
  src/apis/user/controllers/user-connection/user-connection.controller.ts
  src/apis/user/controllers/user-connection/user-connection.swagger.ts
  src/apis/user/domain/user-connection/blog/blog.entity-interface.ts
  src/apis/user/domain/user-connection/blog/blog.entity.ts
  src/apis/user/domain/user-connection/chat-room/chat-room.entity-interface.ts
  src/apis/user/domain/user-connection/chat-room/chat-room.entity.ts
  src/apis/user/domain/user-connection/user-connection.entity-interface.ts
  src/apis/user/domain/user-connection/user-connection.entity.ts
  src/apis/user/domain/user.entity.ts
  src/apis/user/dtos/user-connection/blog/request/create-blog.request-body-dto.ts
  src/apis/user/dtos/user-connection/blog/response/blog.response-dto.ts
  src/apis/user/dtos/user-connection/chat-room/request/create-chat-room.request-body-dto.ts
  src/apis/user/dtos/user-connection/chat-room/response/chat-room.response-dto.ts
  src/apis/user/dtos/user-connection/response/user-connection.response-dto.ts
  src/apis/user/mappers/blog.mapper.ts
  src/apis/user/mappers/chat-room.mapper.ts
  src/apis/user/mappers/user-connection.mapper.ts
  src/apis/user/queries/user-connection/find-one-user-connection/find-one-user-connection.query-handler.ts
  src/apis/user/queries/user-connection/find-one-user-connection/find-one-user-connection.query.ts
  src/apis/user/repositories/user.repository-port.ts
  src/apis/user/repositories/user.repository.ts
  src/apis/user/user.module.ts
  src/configs/app.route.ts
  src/libs/exceptions/http.exception.ts
  src/libs/exceptions/types/errors/auth/auth-error-code.constant.ts
  src/libs/exceptions/types/errors/blog/blog-error-code.constant.ts
  src/libs/exceptions/types/errors/blog/blog-error-message.constant.ts
  src/libs/exceptions/types/errors/chat-room/chat-room-error-code.constant.ts
  src/libs/exceptions/types/errors/chat-room/chat-room-error-message.constant.ts
  src/libs/exceptions/types/errors/common/common-error-code.constant.ts
  src/libs/exceptions/types/errors/error-code.constant.ts
  src/libs/exceptions/types/errors/error-message.constant.ts
  src/libs/exceptions/types/errors/user-connection/user-connection-error-code.constant.ts
  src/libs/exceptions/types/errors/user-connection/user-error-message.constant.ts
  src/libs/exceptions/types/errors/user/user-error-code.constant.ts
  src/libs/exceptions/types/errors/user/user-error-message.constant.ts
  src/libs/types/type.ts
Labels: Feat

#46 Deploy to main
  prisma/migrations/20250113094556_create_chat_rooms_and_blogs/migration.sql
  prisma/schema.prisma
  src/apis/user/commands/user-connection/blog/create-blog/create-blog.command-handler.ts
  src/apis/user/commands/user-connection/blog/create-blog/create-blog.command.ts
  src/apis/user/commands/user-connection/chat-room/create-chat-room/create-chat-room.command-handler.ts
  src/apis/user/commands/user-connection/chat-room/create-chat-room/create-chat-room.command.ts
  src/apis/user/commands/user-connection/create-user-connection/create-user-connection.command-handler.ts
  src/apis/user/commands/user-connection/update-user-connection/update-user-connection.command-handler.ts
  src/apis/user/controllers/user-connection/blog/blog.controller.ts
  src/apis/user/controllers/user-connection/blog/blog.swagger.ts
  src/apis/user/controllers/user-connection/chat-room/chat-room.controller.ts
  src/apis/user/controllers/user-connection/chat-room/chat-room.swagger.ts
  src/apis/user/controllers/user-connection/user-connection.controller.ts
  src/apis/user/controllers/user-connection/user-connection.swagger.ts
  src/apis/user/domain/user-connection/blog/blog.entity-interface.ts
  src/apis/user/domain/user-connection/blog/blog.entity.ts
  src/apis/user/domain/user-connection/chat-room/chat-room.entity-interface.ts
  src/apis/user/domain/user-connection/chat-room/chat-room.entity.ts
  src/apis/user/domain/user-connection/user-connection.entity-interface.ts
  src/apis/user/domain/user-connection/user-connection.entity.ts
  src/apis/user/domain/user.entity.ts
  src/apis/user/dtos/user-connection/blog/request/create-blog.request-body-dto.ts
  src/apis/user/dtos/user-connection/blog/response/blog.response-dto.ts
  src/apis/user/dtos/user-connection/chat-room/request/create-chat-room.request-body-dto.ts
  src/apis/user/dtos/user-connection/chat-room/response/chat-room.response-dto.ts
  src/apis/user/dtos/user-connection/response/user-connection.response-dto.ts
  src/apis/user/mappers/blog.mapper.ts
  src/apis/user/mappers/chat-room.mapper.ts
  src/apis/user/mappers/user-connection.mapper.ts
  src/apis/user/queries/user-connection/find-one-user-connection/find-one-user-connection.query-handler.ts
  src/apis/user/queries/user-connection/find-one-user-connection/find-one-user-connection.query.ts
  src/apis/user/repositories/user.repository-port.ts
  src/apis/user/repositories/user.repository.ts
  src/apis/user/user.module.ts
  src/configs/app.route.ts
  src/libs/exceptions/http.exception.ts
  src/libs/exceptions/types/errors/auth/auth-error-code.constant.ts
  src/libs/exceptions/types/errors/blog/blog-error-code.constant.ts
  src/libs/exceptions/types/errors/blog/blog-error-message.constant.ts
  src/libs/exceptions/types/errors/chat-room/chat-room-error-code.constant.ts
  src/libs/exceptions/types/errors/chat-room/chat-room-error-message.constant.ts
  src/libs/exceptions/types/errors/common/common-error-code.constant.ts
  src/libs/exceptions/types/errors/error-code.constant.ts
  src/libs/exceptions/types/errors/error-message.constant.ts
  src/libs/exceptions/types/errors/user-connection/user-connection-error-code.constant.ts
  src/libs/exceptions/types/errors/user-connection/user-error-message.constant.ts
  src/libs/exceptions/types/errors/user/user-error-code.constant.ts
  src/libs/exceptions/types/errors/user/user-error-message.constant.ts
  src/libs/types/type.ts
Labels: Feat

#49 Prisma ERD 추가
  .dockerignore
  ERD.svg
  package-lock.json
  package.json
  prisma/schema.prisma
Labels: Doc

#58 erd generator disable
  prisma/schema.prisma
Labels: Refactor

#59 Deploy to main
  prisma/schema.prisma
Labels: Refactor

#60 Deploy commit
  src/main.ts
Labels: Deploy

#61 Deploy to main
  src/main.ts
Labels: Deploy

#62 채팅방 생성 로직 수정 및 blog, chat-room api endpoint 수정
  src/configs/app.route.ts
  src/features/blog/commands/create-blog/create-blog.command-handler.ts
  src/features/blog/repositories/blog.repository-port.ts
  src/features/blog/repositories/blog.repository.ts
  src/features/chat-room/commands/create-chat-room/create-chat-room.command-handler.ts
  src/features/chat-room/commands/create-chat-room/create-chat-room.command.ts
  src/features/chat-room/controllers/chat-room.controller.ts
  src/features/user/user-connection/controllers/user-connection.controller.ts
Labels: Refactor

#63 Deploy to main
  src/configs/app.route.ts
  src/features/blog/commands/create-blog/create-blog.command-handler.ts
  src/features/blog/repositories/blog.repository-port.ts
  src/features/blog/repositories/blog.repository.ts
  src/features/chat-room/commands/create-chat-room/create-chat-room.command-handler.ts
  src/features/chat-room/commands/create-chat-room/create-chat-room.command.ts
  src/features/chat-room/controllers/chat-room.controller.ts
  src/features/user/user-connection/controllers/user-connection.controller.ts
Labels: Refactor

#64 prisma schema 수정 및 erd 생성 위치 수정, dockerfile 내에 env 추가
  Dockerfile
  prisma/ERD.svg
  prisma/migrations/20250121073355_add_unique_index_in_blog_post_tags_tags/migration.sql
  prisma/schema.prisma
Labels: Feat, Modify

#66 prisma-erd-generator 삭제
  Dockerfile
  prisma/schema.prisma
Labels: Delete

#68 POST blog-posts API 추가
  prisma/migrations/20250122020821_add_user_id_in_tags/migration.sql
  prisma/schema.prisma
  src/features/blog-post/blog-post-tag/blog-post-tag.module.ts
  src/features/blog-post/blog-post-tag/domain/blog-post-tag.entity-interface.ts
  src/features/blog-post/blog-post-tag/domain/blog-post-tag.entity.ts
  src/features/blog-post/blog-post-tag/mappers/blog-post-tag.mapper.ts
  src/features/blog-post/blog-post-tag/repositories/blog-post-tag.repository-port.ts
  src/features/blog-post/blog-post-tag/repositories/blog-post-tag.repository.ts
  src/features/blog-post/blog-post-tag/tokens/di.token.ts
  src/features/blog-post/blog-post.module.ts
  src/features/blog-post/commands/create-blog-post/create-blog-post.command-handler.ts
  src/features/blog-post/commands/create-blog-post/create-blog-post.command.ts
  src/features/blog-post/controllers/blog-post.controller.ts
  src/features/blog-post/controllers/blog-post.swagger.ts
  src/features/blog-post/domain/blog-post.entity-interface.ts
  src/features/blog-post/domain/blog-post.entity.ts
  src/features/blog-post/dtos/request/create-blog-post.request-body-dto.ts
  src/features/blog-post/dtos/response/blog-post.response-dto.ts
  src/features/blog-post/mappers/blog-post.mapper.ts
  src/features/blog-post/repositories/blog-post.repository-port.ts
  src/features/blog-post/repositories/blog-post.repository.ts
  src/features/blog-post/tokens/di.token.ts
  src/features/blog-post/types/blog-post.type.ts
  src/features/blog/blog.module.ts
  src/features/blog/controllers/blog.controller.ts
  src/features/blog/domain/blog.entity.ts
  src/features/chat-room/controllers/chat-room.controller.ts
  src/features/features.module.ts
  src/features/tag/domain/tag.entity-interface.ts
  src/features/tag/domain/tag.entity.ts
  src/features/tag/dtos/response/hydrated-tag.response-dto.ts
  src/features/tag/mappers/tag.mapper.ts
  src/features/tag/repositories/tag.repository-port.ts
  src/features/tag/repositories/tag.repository.ts
  src/features/tag/tag.module.ts
  src/features/tag/tokens/di.token.ts
  src/libs/exceptions/types/errors/error-message.constant.ts
  src/libs/exceptions/types/errors/user-connection/user-connection-error-code.constant.ts
  src/libs/exceptions/types/errors/user-connection/user-connection-error-message.constant.ts
  src/libs/guard.ts
Labels: Feat

#69 Deploy to main
  prisma/migrations/20250122020821_add_user_id_in_tags/migration.sql
  prisma/schema.prisma
  src/features/blog-post/blog-post-tag/blog-post-tag.module.ts
  src/features/blog-post/blog-post-tag/domain/blog-post-tag.entity-interface.ts
  src/features/blog-post/blog-post-tag/domain/blog-post-tag.entity.ts
  src/features/blog-post/blog-post-tag/mappers/blog-post-tag.mapper.ts
  src/features/blog-post/blog-post-tag/repositories/blog-post-tag.repository-port.ts
  src/features/blog-post/blog-post-tag/repositories/blog-post-tag.repository.ts
  src/features/blog-post/blog-post-tag/tokens/di.token.ts
  src/features/blog-post/blog-post.module.ts
  src/features/blog-post/commands/create-blog-post/create-blog-post.command-handler.ts
  src/features/blog-post/commands/create-blog-post/create-blog-post.command.ts
  src/features/blog-post/controllers/blog-post.controller.ts
  src/features/blog-post/controllers/blog-post.swagger.ts
  src/features/blog-post/domain/blog-post.entity-interface.ts
  src/features/blog-post/domain/blog-post.entity.ts
  src/features/blog-post/dtos/request/create-blog-post.request-body-dto.ts
  src/features/blog-post/dtos/response/blog-post.response-dto.ts
  src/features/blog-post/mappers/blog-post.mapper.ts
  src/features/blog-post/repositories/blog-post.repository-port.ts
  src/features/blog-post/repositories/blog-post.repository.ts
  src/features/blog-post/tokens/di.token.ts
  src/features/blog-post/types/blog-post.type.ts
  src/features/blog/blog.module.ts
  src/features/blog/controllers/blog.controller.ts
  src/features/blog/domain/blog.entity.ts
  src/features/chat-room/controllers/chat-room.controller.ts
  src/features/features.module.ts
  src/features/tag/domain/tag.entity-interface.ts
  src/features/tag/domain/tag.entity.ts
  src/features/tag/dtos/response/hydrated-tag.response-dto.ts
  src/features/tag/mappers/tag.mapper.ts
  src/features/tag/repositories/tag.repository-port.ts
  src/features/tag/repositories/tag.repository.ts
  src/features/tag/tag.module.ts
  src/features/tag/tokens/di.token.ts
  src/libs/exceptions/types/errors/error-message.constant.ts
  src/libs/exceptions/types/errors/user-connection/user-connection-error-code.constant.ts
  src/libs/exceptions/types/errors/user-connection/user-connection-error-message.constant.ts
  src/libs/guard.ts
Labels: Feat

#71 Deploy to main
  src/bootstrap.service.ts
Labels: Doc

#74 ApiSecurity 추가
  src/features/auth/controllers/auth.controller.ts
  src/features/blog-post/controllers/blog-post.controller.ts
  src/features/blog/controllers/blog.controller.ts
  src/features/chat-room/controllers/chat-room.controller.ts
  src/features/user/controllers/user.controller.ts
  src/features/user/user-connection/controllers/user-connection.controller.ts
Labels: Doc

#75 Deploy to main
  src/features/auth/controllers/auth.controller.ts
  src/features/blog-post/controllers/blog-post.controller.ts
  src/features/blog/controllers/blog.controller.ts
  src/features/chat-room/controllers/chat-room.controller.ts
  src/features/user/controllers/user.controller.ts
  src/features/user/user-connection/controllers/user-connection.controller.ts
Labels: Doc

#76 Hydrate 방식 변경
  src/bootstrap.service.ts
  src/features/blog-post/commands/create-blog-post/create-blog-post.command-handler.ts
  src/features/blog-post/domain/blog-post.entity.ts
  src/features/blog/domain/blog.entity.ts
  src/features/chat-room/domain/chat-room.entity.ts
  src/features/tag/domain/tag.entity.ts
  src/features/user/domain/user.entity.ts
  src/features/user/queries/user-connection/find-one-user-connection/find-one-user-connection.query-handler.ts
  src/features/user/queries/user-connection/find-one-user-connection/find-one-user-connection.query.ts
  src/features/user/queries/user-connection/find-user-connections/find-user-connections.query-handler.ts
  src/features/user/queries/user-connection/find-user-connections/find-user-connections.query.ts
  src/features/user/user-connection/domain/user-connection.entity.ts
  src/features/user/user-connection/queries/find-user-connections/find-user-connections.query-handler.ts
Labels: Refactor

#77 Deploy to main
  src/bootstrap.service.ts
  src/features/blog-post/commands/create-blog-post/create-blog-post.command-handler.ts
  src/features/blog-post/domain/blog-post.entity.ts
  src/features/blog/domain/blog.entity.ts
  src/features/chat-room/domain/chat-room.entity.ts
  src/features/tag/domain/tag.entity.ts
  src/features/user/domain/user.entity.ts
  src/features/user/queries/user-connection/find-one-user-connection/find-one-user-connection.query-handler.ts
  src/features/user/queries/user-connection/find-one-user-connection/find-one-user-connection.query.ts
  src/features/user/queries/user-connection/find-user-connections/find-user-connections.query-handler.ts
  src/features/user/queries/user-connection/find-user-connections/find-user-connections.query.ts
  src/features/user/user-connection/domain/user-connection.entity.ts
  src/features/user/user-connection/queries/find-user-connections/find-user-connections.query-handler.ts
Labels: Refactor

#78 CORS 에러 수정
  prisma/migrations/20250124084227_create_attachments/migration.sql
  prisma/schema.prisma
  src/bootstrap.service.ts
  src/features/attachment/application/event-handlers/create-user-email-verify-token.domain-event-handler.ts
  src/features/attachment/attachment.module.ts
  src/features/attachment/commands/create-user/create-user.command-handler.ts
  src/features/attachment/commands/create-user/create-user.command.ts
  src/features/attachment/commands/send-password-change-verification-email/send-password-change-verification-email.command-handler.ts
  src/features/attachment/commands/send-password-change-verification-email/send-password-change-verification-email.command.ts
  src/features/attachment/commands/send-verification-email/send-verification-email.command-handler.ts
  src/features/attachment/commands/send-verification-email/send-verification-email.command.ts
  src/features/attachment/commands/update-user-password/update-user-password.command-handler.ts
  src/features/attachment/commands/update-user-password/update-user-password.command.ts
  src/features/attachment/commands/verify-user-email/verify-user-email.command-handler.ts
  src/features/attachment/commands/verify-user-email/verify-user-email.command.ts
  src/features/attachment/controllers/user.controller.ts
  src/features/attachment/controllers/user.swagger.ts
  src/features/attachment/domain/events/user-created.event.ts
  src/features/attachment/domain/events/user-is-email-verified-modified.event.ts
  src/features/attachment/domain/events/user-password-updated.event.ts
  src/features/attachment/domain/user-verify-token/user-verify-token.entity-interface.ts
  src/features/attachment/domain/user-verify-token/user-verify-token.entity.ts
  src/features/attachment/domain/user.entity-interface.ts
  src/features/attachment/domain/user.entity.ts
  src/features/attachment/dtos/request/find-users.request-query-dto.ts
  src/features/attachment/dtos/request/send-password-change-verification-email.request-dto.ts
  src/features/attachment/dtos/request/update-password.request-dto.ts
  src/features/attachment/dtos/response/hydrated-user.response-dto.ts
  src/features/attachment/dtos/response/user.response-dto.ts
  src/features/attachment/mappers/user-verify-token.mapper.ts
  src/features/attachment/mappers/user.mapper.ts
  src/features/attachment/queries/find-users/find-users.query-handler.ts
  src/features/attachment/queries/find-users/find-users.query.ts
  src/features/attachment/repositories/user.repository-port.ts
  src/features/attachment/repositories/user.repository.ts
  src/features/attachment/tokens/di.token.ts
  src/features/attachment/types/user.constant.ts
  src/features/attachment/types/user.type.ts
Labels: Setup

#79 Deploy to main
  prisma/migrations/20250124084227_create_attachments/migration.sql
  prisma/schema.prisma
  src/bootstrap.service.ts
  src/features/attachment/application/event-handlers/create-user-email-verify-token.domain-event-handler.ts
  src/features/attachment/attachment.module.ts
  src/features/attachment/commands/create-user/create-user.command-handler.ts
  src/features/attachment/commands/create-user/create-user.command.ts
  src/features/attachment/commands/send-password-change-verification-email/send-password-change-verification-email.command-handler.ts
  src/features/attachment/commands/send-password-change-verification-email/send-password-change-verification-email.command.ts
  src/features/attachment/commands/send-verification-email/send-verification-email.command-handler.ts
  src/features/attachment/commands/send-verification-email/send-verification-email.command.ts
  src/features/attachment/commands/update-user-password/update-user-password.command-handler.ts
  src/features/attachment/commands/update-user-password/update-user-password.command.ts
  src/features/attachment/commands/verify-user-email/verify-user-email.command-handler.ts
  src/features/attachment/commands/verify-user-email/verify-user-email.command.ts
  src/features/attachment/controllers/user.controller.ts
  src/features/attachment/controllers/user.swagger.ts
  src/features/attachment/domain/events/user-created.event.ts
  src/features/attachment/domain/events/user-is-email-verified-modified.event.ts
  src/features/attachment/domain/events/user-password-updated.event.ts
  src/features/attachment/domain/user-verify-token/user-verify-token.entity-interface.ts
  src/features/attachment/domain/user-verify-token/user-verify-token.entity.ts
  src/features/attachment/domain/user.entity-interface.ts
  src/features/attachment/domain/user.entity.ts
  src/features/attachment/dtos/request/find-users.request-query-dto.ts
  src/features/attachment/dtos/request/send-password-change-verification-email.request-dto.ts
  src/features/attachment/dtos/request/update-password.request-dto.ts
  src/features/attachment/dtos/response/hydrated-user.response-dto.ts
  src/features/attachment/dtos/response/user.response-dto.ts
  src/features/attachment/mappers/user-verify-token.mapper.ts
  src/features/attachment/mappers/user.mapper.ts
  src/features/attachment/queries/find-users/find-users.query-handler.ts
  src/features/attachment/queries/find-users/find-users.query.ts
  src/features/attachment/repositories/user.repository-port.ts
  src/features/attachment/repositories/user.repository.ts
  src/features/attachment/tokens/di.token.ts
  src/features/attachment/types/user.constant.ts
  src/features/attachment/types/user.type.ts
Labels: Setup

#81 Deploy to main
  src/bootstrap.service.ts
Labels: Setup

#72 채팅 메시지 페이지네이션 API, socket.io 채팅 기능 구현
  package-lock.json
  package.json
  prisma/ERD.svg
  prisma/migrations/20250119075631_create_chat_message_model/migration.sql
  prisma/migrations/20250123063302_modify_chat_message_message_type/migration.sql
  prisma/schema.prisma
  src/configs/app.route.ts
  src/features/chat-message/chat-message.module.ts
  src/features/chat-message/commands/create-message/create-chat-message.command-handler.ts
  src/features/chat-message/commands/create-message/create-chat-message.command.ts
  src/features/chat-message/controllers/chat-message.controller.ts
  src/features/chat-message/controllers/chat-message.swagger.ts
  src/features/chat-message/domain/chat-message.entity-interface.ts
  src/features/chat-message/domain/chat-message.entity.ts
  src/features/chat-message/dtos/request/find-chat-messages.request-query-dto.ts
  src/features/chat-message/dtos/response/chat-message.response-dto.ts
  src/features/chat-message/dtos/socket/create-chat-message.dto.ts
  src/features/chat-message/dtos/socket/enter-chat.dto.ts
  src/features/chat-message/dtos/socket/socket-with-user.dto.ts
  src/features/chat-message/gateways/chat-message.gateway.ts
  src/features/chat-message/mappers/chat-message.mapper.ts
  src/features/chat-message/queries/find-chat-messages/find-chat-messages.query-handler.ts
  src/features/chat-message/queries/find-chat-messages/find-chat-messages.query.ts
  src/features/chat-message/repositories/chat-message.repository-port.ts
  src/features/chat-message/repositories/chat-message.repository.ts
  src/features/chat-message/tokens/di.token.ts
  src/features/chat-room/chat-room.module.ts
  src/features/chat-room/domain/chat-room.entity.ts
  src/features/chat-room/queries/exists-chat-room.query-handler.ts
  src/features/chat-room/queries/exists-chat-room.query.ts
  src/features/chat-room/repositories/chat-room.repository-port.ts
  src/features/chat-room/repositories/chat-room.repository.ts
  src/features/features.module.ts
  src/features/user/types/user.constant.ts
  src/features/user/user-connection/repositories/user-connection.repository-port.ts
  src/features/user/user-connection/repositories/user-connection.repository.ts
  src/features/user/user.module.ts
  src/libs/exceptions/socket/filters/socket-catch-http.exception-filter.ts
  src/libs/guards/guard.module.ts
  src/libs/guards/providers/socket-jwt-bearer-auth.guard.ts
Labels: Feat

#83 Deploy to main
  package-lock.json
  package.json
  prisma/ERD.svg
  prisma/migrations/20250119075631_create_chat_message_model/migration.sql
  prisma/migrations/20250123063302_modify_chat_message_message_type/migration.sql
  prisma/schema.prisma
  src/configs/app.route.ts
  src/features/chat-message/chat-message.module.ts
  src/features/chat-message/commands/create-message/create-chat-message.command-handler.ts
  src/features/chat-message/commands/create-message/create-chat-message.command.ts
  src/features/chat-message/controllers/chat-message.controller.ts
  src/features/chat-message/controllers/chat-message.swagger.ts
  src/features/chat-message/domain/chat-message.entity-interface.ts
  src/features/chat-message/domain/chat-message.entity.ts
  src/features/chat-message/dtos/request/find-chat-messages.request-query-dto.ts
  src/features/chat-message/dtos/response/chat-message.response-dto.ts
  src/features/chat-message/dtos/socket/create-chat-message.dto.ts
  src/features/chat-message/dtos/socket/enter-chat.dto.ts
  src/features/chat-message/dtos/socket/socket-with-user.dto.ts
  src/features/chat-message/gateways/chat-message.gateway.ts
  src/features/chat-message/mappers/chat-message.mapper.ts
  src/features/chat-message/queries/find-chat-messages/find-chat-messages.query-handler.ts
  src/features/chat-message/queries/find-chat-messages/find-chat-messages.query.ts
  src/features/chat-message/repositories/chat-message.repository-port.ts
  src/features/chat-message/repositories/chat-message.repository.ts
  src/features/chat-message/tokens/di.token.ts
  src/features/chat-room/chat-room.module.ts
  src/features/chat-room/domain/chat-room.entity.ts
  src/features/chat-room/queries/exists-chat-room.query-handler.ts
  src/features/chat-room/queries/exists-chat-room.query.ts
  src/features/chat-room/repositories/chat-room.repository-port.ts
  src/features/chat-room/repositories/chat-room.repository.ts
  src/features/features.module.ts
  src/features/user/types/user.constant.ts
  src/features/user/user-connection/repositories/user-connection.repository-port.ts
  src/features/user/user-connection/repositories/user-connection.repository.ts
  src/features/user/user.module.ts
  src/libs/exceptions/socket/filters/socket-catch-http.exception-filter.ts
  src/libs/guards/guard.module.ts
  src/libs/guards/providers/socket-jwt-bearer-auth.guard.ts
Labels: Feat

#84 유저 커넥션 생성 에러 로직 수정
  src/features/user/user-connection/commands/create-user-connection/create-user-connection.command-handler.ts
  src/libs/exceptions/types/errors/user-connection/user-connection-error-code.constant.ts
  src/libs/exceptions/types/errors/user-connection/user-connection-error-message.constant.ts
Labels: Bugfix

#85 Deploy to main
  src/features/user/user-connection/commands/create-user-connection/create-user-connection.command-handler.ts
  src/libs/exceptions/types/errors/user-connection/user-connection-error-code.constant.ts
  src/libs/exceptions/types/errors/user-connection/user-connection-error-message.constant.ts
Labels: Bugfix
