Repository honey-moa/honey-moa-server, pull requests merged in 2025-03, with the labels that each got.

#179 BlogPost 도메인 관련 로직 리팩터링
  src/features/attachment/applications/event-handlers/create-thumbnail-attachment-when-blog-post-created.domain-event-handler.ts
  src/features/attachment/applications/event-handlers/delete-attachments-when-blog-post-updated.domain-event-hanlder.ts
  src/features/attachment/applications/event-handlers/update-thumbnail-attachment-when-blog-post-updated.domain-event-handler.ts
  src/features/attachment/attachment.module.ts
  src/features/attachment/domain/attachment.entity.ts
  src/features/blog-post/application/event-handlers/create-contents-attachments-when-blog-post-created.domain-event-handler.ts
  src/features/blog-post/application/event-handlers/create-tags-when-blog-post-created.domain-event-handler.ts
  src/features/blog-post/application/event-handlers/update-contents-attachments-when-blog-post-updated.domain-event-handler.ts
  src/features/blog-post/application/event-handlers/update-tags-when-blog-post-updated.domain-event-handler.ts
  src/features/blog-post/blog-post-attachment/domain/blog-post-attachment.entity.ts
  src/features/blog-post/blog-post.module.ts
  src/features/blog-post/commands/create-blog-post/create-blog-post.command-handler.ts
  src/features/blog-post/commands/patch-update-blog-post/patch-update-blog-post.command-handler.ts
  src/features/blog-post/controllers/blog-post.controller.ts
  src/features/blog-post/domain/blog-post.entity-interface.ts
  src/features/blog-post/domain/blog-post.entity.ts
  src/features/blog-post/domain/domain-services/blog-post.domain-service.ts
  src/features/blog-post/domain/events/blog-post-created.domain-event.ts
  src/features/blog-post/domain/events/blog-post-thumbnail-imgae-path-updated.domain-event.ts
  src/features/blog-post/domain/events/blog-post-updated.domain-event.ts
  src/features/blog-post/repositories/blog-post.repository-port.ts
  src/features/blog-post/repositories/blog-post.repository.ts
  src/features/blog/domain/blog.errors.ts
  src/features/tag/commands/create-new-tags/create-new-tags.command-handler.ts
  src/features/tag/commands/create-new-tags/create-new-tags.command.ts
  src/features/tag/tag.module.ts
Labels: Refactor

#180 Deploy to main
  src/features/attachment/applications/event-handlers/create-thumbnail-attachment-when-blog-post-created.domain-event-handler.ts
  src/features/attachment/applications/event-handlers/delete-attachments-when-blog-post-updated.domain-event-hanlder.ts
  src/features/attachment/applications/event-handlers/update-thumbnail-attachment-when-blog-post-updated.domain-event-handler.ts
  src/features/attachment/attachment.module.ts
  src/features/attachment/domain/attachment.entity.ts
  src/features/blog-post/application/event-handlers/create-contents-attachments-when-blog-post-created.domain-event-handler.ts
  src/features/blog-post/application/event-handlers/create-tags-when-blog-post-created.domain-event-handler.ts
  src/features/blog-post/application/event-handlers/update-contents-attachments-when-blog-post-updated.domain-event-handler.ts
  src/features/blog-post/application/event-handlers/update-tags-when-blog-post-updated.domain-event-handler.ts
  src/features/blog-post/blog-post-attachment/domain/blog-post-attachment.entity.ts
  src/features/blog-post/blog-post.module.ts
  src/features/blog-post/commands/create-blog-post/create-blog-post.command-handler.ts
  src/features/blog-post/commands/patch-update-blog-post/patch-update-blog-post.command-handler.ts
  src/features/blog-post/controllers/blog-post.controller.ts
  src/features/blog-post/domain/blog-post.entity-interface.ts
  src/features/blog-post/domain/blog-post.entity.ts
  src/features/blog-post/domain/domain-services/blog-post.domain-service.ts
  src/features/blog-post/domain/events/blog-post-created.domain-event.ts
  src/features/blog-post/domain/events/blog-post-thumbnail-imgae-path-updated.domain-event.ts
  src/features/blog-post/domain/events/blog-post-updated.domain-event.ts
  src/features/blog-post/repositories/blog-post.repository-port.ts
  src/features/blog-post/repositories/blog-post.repository.ts
  src/features/blog/domain/blog.errors.ts
  src/features/tag/commands/create-new-tags/create-new-tags.command-handler.ts
  src/features/tag/commands/create-new-tags/create-new-tags.command.ts
  src/features/tag/tag.module.ts
Labels: Refactor

#184 이메일 재전송 시간, 버그 로직 수정
  src/features/user/domain/user-verify-token/user-verify-token.entity.ts
  src/features/user/queries/find-one-user/find-one-user.query-handler.ts
  src/features/user/queries/find-users/find-users.query-handler.ts
  src/libs/exceptions/server-errors/filters/zod-error.exception-filter.ts
  src/libs/exceptions/services/http-exception.service.ts
  src/libs/interceptors/logging/request-response-logging.interceptor.ts
Labels: Modify

#185 Deploy to main
  src/features/user/domain/user-verify-token/user-verify-token.entity.ts
  src/features/user/queries/find-one-user/find-one-user.query-handler.ts
  src/features/user/queries/find-users/find-users.query-handler.ts
  src/libs/exceptions/server-errors/filters/zod-error.exception-filter.ts
  src/libs/exceptions/services/http-exception.service.ts
  src/libs/interceptors/logging/request-response-logging.interceptor.ts
Labels: Modify

#186 userVerifyTokenSchema 수정
  src/features/blog-post/blog-post-comment/controllers/blog-post-comment.swagger.ts
  src/features/user/mappers/user-verify-token.mapper.ts
Labels: Modify

#187 Deploy to main
  src/features/blog-post/blog-post-comment/controllers/blog-post-comment.swagger.ts
  src/features/user/mappers/user-verify-token.mapper.ts
Labels: Modify

#190 develop 서버 구축 및 CI/CD 구축으로 배포 자동화
  .github/workflows/app-dev.yml
  Dockerfile.dev
  nginx.conf
Labels: Deploy

#191 리드미 작성
  .dockerignore
  README.md
  assets/architecture/dev-architecture.png
  assets/architecture/prod-architecture.png
  assets/erd/ERD.svg
  assets/logo/188959312.jpeg
  assets/team/hobijeong.jpeg
  assets/team/lee.jpeg
  assets/team/nicodora.jpeg
  assets/team/parkhyunwoo.png
  docs/BRANCH_STRATEGY.md
  docs/COMMIT_CONVENTION.md
  docs/TECH_STACK.md
  src/main.ts
Labels: Doc

#195 Deploy to main
  .dockerignore
  .github/workflows/app-dev.yml
  Dockerfile.dev
  README.md
  assets/architecture/dev-architecture.png
  assets/architecture/prod-architecture.png
  assets/erd/ERD.svg
  assets/logo/188959312.jpeg
  assets/team/hobijeong.jpeg
  assets/team/lee.jpeg
  assets/team/nicodora.jpeg
  assets/team/parkhyunwoo.png
  docs/BRANCH_STRATEGY.md
  docs/COMMIT_CONVENTION.md
  docs/TECH_STACK.md
  nginx.conf
  src/features/blog-post/queries/find-blog-posts-from-blog/find-blog-posts-from-blog.query-handler.ts
  src/features/blog-post/queries/find-one-blog-post/find-one-blog-post.query-handler.ts
  src/features/blog-post/queries/find-public-blog-posts/find-public-blog-posts.query-handler.ts
  src/features/blog/queries/find-one-blog-by-user-id/find-one-blog-by-user-id.query-handler.ts
  src/features/user/queries/find-one-user/find-one-user.query-handler.ts
  src/main.ts
Labels: Doc, Feat, Bugfix

#197 채팅방 입장, 메시지 전송 시에 클라이언트로 ack 전송
  src/features/chat-message/gateways/chat-message.gateway.ts
Labels: Modify

#198 Deploy to main
  src/features/chat-message/gateways/chat-message.gateway.ts
Labels: Modify
